version: '3.5'

services:

  react:
    container_name: web-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        AMBIENTE: "Development"
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3000:80'
